export const theme = {
  light: {
    colors: {
      mainBgColor: "#fdfffc",
      mainTextColor: "#02040f",
      secondaryTextColor: "#001524",
      lightTextColor: "#868e96",
      buttonTextColor: "#f8f9fa",
      buttonBgColor: "#0353a4",
      buttonBgHoverColor: "#0466c8",
      headerButtonBgAccentColor: "#FDB349",
      headerButtonTextAccentColor: "#02040f",
      formBorderColor: "#dee2e6",
      youtubeColor: "#cd201f",
      linkedinColor: "#0a66c2",
      stackoverflowColor: "#F48024",
      blackIconsColor: "#000814",
      linkColor: "#37A4FE",
      switcherHoverBg: "#ced4da60",
      heroBgLightGreyColor: "#f1f3f5",
    },
  },
  dark: {
    colors: {
      mainBgColor: "#0c0a09",
      mainTextColor: "#fdfffc",
      secondaryTextColor: "#f8f9fa",
      lightTextColor: "#868e96",
      buttonTextColor: "#f8f9fa",
      buttonBgColor: "#0353a4",
      buttonBgHoverColor: "#0466c8",
      headerButtonBgAccentColor: "#FDB349",
      headerButtonTextAccentColor: "#02040f",
      formBorderColor: "#dee2e6",
      youtubeColor: "#cd201f",
      linkedinColor: "#0a66c2",
      stackoverflowColor: "#F48024",
      blackIconsColor: "#fafaf9",
      linkColor: "#37A4FE",
      switcherHoverBg: "#e9ecef60",
      heroBgLightGreyColor: "#f1f3f5",
    },
  },
};
