name: Frontend Deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
  pull_request:
    types:
      - opened
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install frontend dependencies
        run: npm ci --prefix frontend
      - name: Build frontend
        run: npm run build --prefix frontend
      - name: Deploy frontend
        run: echo "Deploying frontend..."
