name: Frontend Deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
  pull_request:
    types:
      - opened
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - name: Install frontend dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --prefix frontend
      - name: Build frontend
        continue-on-error: true
        id: build-frontend
        run: npm run build --prefix frontend
      - name: Upload build artifacts
        # if: failure() && steps.build-frontend.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: ./frontend/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Download build artifacts
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: Deploy frontend
        run: echo "Deploying frontend..."

  report:
    needs: [build, deploy]
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Report failure
        run: |
          echo "❌ Workflow failed! Check build and deploy logs for details."
          echo ${{ toJSON(github) }}
